services:
  - type: web
    name: omniroute
    runtime: node
    plan: free
    region: oregon
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: DATA_DIR
        value: ./.omniroute
      - key: STORAGE_ENCRYPTION_KEY
        value: b26707cc3ad0b6868374dc304ae9ee5dd468facfe57074c1ed6fe2267bcb8b81
      - key: OMNIROUTE_SERVER_HOST
        value: 0.0.0.0
      - key: NODE_ENV
        value: production
      - key: NODE_OPTIONS
        value: --max-old-space-size=300
      - key: OMNIROUTE_MEMORY_MB
        value: "300"
